<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lesson 01 - PHP Introduction</title>
</head>
<body>

<h1>PHP & MySQL Course</h1>
<p>This text is written in HTML.</p>

<?php
// PHP runs on the server and sends the result to the browser.
echo "<p>This text is generated by PHP.</p>";
echo "<p>PHP is running successfully through localhost.</p>";
?>

</body>
</html>
